In [1]:
import sys
import os

# Get the absolute path to the project directory
project_dir = os.path.abspath("..")

# Append the project directory to sys.path
if project_dir not in sys.path:
    sys.path.append(project_dir)
    
from src.predictionModule.LoadupSamples import LoadupSamples
from src.hyperparameterTuning.HelperMetrics import HelperMetrics

import pandas as pd
import numpy as np
import polars as pl
import datetime
import random
import matplotlib.pyplot as plt
import logging
import time
import re

In [ ]:
N = 5
T = 1
arr_open = [1.000,
            1.000,
            1.000,
            1.000,
            1.000]

arr_low  = [0.979,
            0.970,
            0.990,
            1.020,
            0.995]

arr_high = [1.005,
            1.005,
            1.025,
            1.040,
            1.008]

arr      = [1.000,  # fallback if no hit
            0.975,
            1.000,
            1.030,
            1.010]

arr = np.array(arr)
arr_low =  np.array(arr_low)
arr_high = np.array(arr_high)
arr_open = np.array(arr_open)

sl = 0.980
tp = 1.020
spread_cost = 0.000
commission = 0.000
out = HelperMetrics.collapse_sl_tp(
    arr, arr_low, arr_high, arr_open,
    sl=sl, tp=tp, spread_cost=spread_cost, commission=commission
)
out

array([0.98, 0.98, 1.02, 1.02, 1.01])

In [ ]:
N = 5
T = 1
arr_open = [[1.000],
            [1.000],
            [1.000],
            [1.000],
            [1.000]]

arr_low  = [[0.979],
            [0.970],
            [0.990],
            [1.020],
            [0.995]]

arr_high = [[1.005],
            [1.021],
            [1.025],
            [1.040],
            [1.008]]

arr      = [[1.000],  # fallback if no hit
            [0.975],
            [1.000],
            [1.030],
            [1.010]]

arr = np.array(arr)
arr_low =  np.array(arr_low)
arr_high = np.array(arr_high)
arr_open = np.array(arr_open)

sl = 0.980
tp = 1.020
spread_cost = 0.000
commission = 0.000
out = HelperMetrics.collapse_sl_tp(
    arr, arr_low, arr_high, arr_open,
    sl=sl, tp=tp, spread_cost=spread_cost, commission=commission
)
# array([0.98, 0.98, 1.02, 1.02, 1.01])
out

array([0.98, 0.98, 1.02, 1.02, 1.01])

In [ ]:
# Five rows demonstrate: SL-by-low, SL-by-open-gap, TP-by-high, TP-by-open-gap, No-hit
arr = np.array([
    [1.00, 1.00, 1.00],   # 0: SL by low (non-gap) at j=0 -> sl - spread_cost
    [1.00, 1.00, 1.00],   # 1: SL by open gap at j=0      -> open
    [1.00, 1.00, 1.00],   # 2: TP by high (non-gap) at j=0-> tp - spread_cost
    [1.00, 1.00, 1.00],   # 3: TP by open gap at j=0      -> open
    [1.00, 1.005, 1.01],  # 4: No hit                      -> last value
])
arr_open = np.array([
    [1.00, 1.00, 1.00],
    [1.00, 1.00, 1.00],
    [1.00, 1.00, 1.00],
    [1.00, 1.00, 1.00],
    [1.00, 1.005, 1.01],
])
arr_low = np.array([
    [0.97, 0.99, 0.99],
    [0.96, 0.99, 0.99],
    [0.99, 0.99, 0.99],
    [0.99, 0.99, 0.99],
    [0.985,0.99, 0.99],
])
arr_high = np.array([
    [1.01, 1.01, 1.01],
    [1.01, 1.01, 1.01],
    [1.03, 1.01, 1.01],
    [1.04, 1.01, 1.01],
    [1.015,1.015,1.015],
])
sl, tp = 0.98, 1.02
out = HelperMetrics.collapse_sl_tp(
    arr, arr_low, arr_high, arr_open,
    sl=sl, tp=tp, spread_cost=0.005, commission=0.0
)
out
#array([0.975, 0.975, 1.015, 1.015, 1.01 ])
# Row-wise interpretation:
# 0 -> 0.98 - 0.005 = 0.975 (SL by low, non-gap)
# 1 -> 0.97           (SL by open gap)
# 2 -> 1.02 - 0.005 = 1.015 (TP by high, non-gap)
# 3 -> 1.03           (TP by open gap)
# 4 -> 1.01           (no threshold hit -> last value)


array([0.975, 0.975, 1.015, 1.015, 1.01 ])

In [ ]:
out = HelperMetrics.collapse_sl_tp(
    arr, arr_low, arr_high, arr_open,
    sl=sl, tp=None, spread_cost=0.005, commission=0.0
)
out
# array([0.975, 0.975, 1.   , 1.   , 1.01 ])

array([0.975, 0.975, 1.   , 1.   , 1.01 ])